# -*- coding: utf-8 -*-
"""main.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1QVBxh-eeLAhHv_cWIGbBlNh68XoTNEHN
"""

from modul_transaction import Transaction

trnsct_123 = Transaction()
trnsct_123.tambah_barang("apel", 20, 3000)
trnsct_123.tambah_barang("jambu", 25, 2500)
trnsct_123.tambah_barang("mangga", 12, 5000)
trnsct_123.tambah_barang("jeruk", 33, 3500)
trnsct_123.cek_order()

trnsct_123.update_nama_barang("apel", "duku")
trnsct_123.cek_order()

trnsct_123.update_jumlah_barang("mangga", 17)
trnsct_123.cek_order()

trnsct_123.update_harga_barang("jambu", 3000)
trnsct_123.cek_order()

trnsct_123.hapus_barang('duku')
trnsct_123.cek_order()

trnsct_123.cek_order()
trnsct_123.total_belanja()

trnsct_123.reset_transaction()
trnsct_123.cek_order()